### ISSUE TITLE
Is it possible to use spreedly GW instead of stripe?

### ISSUE THREAD

**Issue by mazharoddin** [buggy/rails-saas-template#43]
Hi,
Is it possible to use spreedly instead of stripe, right now stripe doesn't support Indian payment GWs and only spreedly has support for PayU gatway, can you please let me know if its possible to use spreedly instead of stripe or is it possible to use PayU GW directly instead of stripe. 
Thanks.

**Comment by buggy** [comment]
This is a starter app. The idea is that you begin with this then make the changes that you require. It's absolutely possible to remove the Stripe support and replace it with any gateway that you want. In many ways that's exactly how it should be used.

**Comment by mazharoddin** [comment]
Thanks, if you can provide some pointers it would be great , like which code i need to modify and which code I may need to add/look into to integrate the payment gateway etc... 
Thanks
